### ISSUE TITLE
Typo error in project description

### ISSUE THREAD

**Issue by atif0075** [marslan70/Email_writing_design#1]
**Email writing UI using HTML, CSS, Javascript** instead of _Email writing UI usong HTML, CSS, Javascript_

<img width="435" alt="Screenshot 2024-02-10 at 5 39 32 PM" src="https://github.com/marslan70/Email_writing_design/assets/64689549/e7a3be5d-51fb-4db9-9a0e-73e0fa79a424">

**Comment by marslan70** [comment]
Ok sir
